InsertWordUI.js showAlert functions makes the Add Word container expa…
awesomememo/frontend-js pull request #21
Opened 2020-11-15 02:27 UTC by tiffanygan

…nd, closes #17

2020-11-21 19:12 UTC, ganneo requested changes
Address comments

2020-11-21 19:12 UTC, ganneo commented on assets/css/style.css
>  }
Don't use hard coded value

2020-11-24 18:54 UTC, ganneo approved these changes
Perfect!

2020-11-24 19:11 UTC, yugan2005 commented
LGTM. Shipit.

2020-11-24 19:11 UTC, merged