Close navbar after clicking outside of it
awesomememo/frontend-js pull request #23
Opened 2020-11-26 21:44 UTC by ganneo

2020-11-27 00:09 UTC, tiffanygan commented on src/streak.js
> +});
This is a very good function, but repeating this in every javascript file seems a bit redundant. Is there a way you can share the same function over files?

2020-11-27 00:56 UTC, tiffanygan requested changes

2020-11-27 00:56 UTC, tiffanygan commented on src/register.js
> +let navOpen = false;
You don't need this anymore because you imported the function from `Util`

2020-11-27 00:56 UTC, tiffanygan commented on src/register.js
> +});
same as line 9

2020-11-27 20:31 UTC, tiffanygan approved these changes

2020-11-27 21:03 UTC, yugan2005 commented on src/lib/Util.js
> +  }
This logic need be discussed. 
1. We should not `addEventListener` and `removeEventListener` repetitively.
2. Instead, we should use event delegation
3. We can check the attribute to get whether the navbar is collapsed or not

2020-11-28 18:53 UTC, tiffanygan requested changes

2020-11-28 18:53 UTC, tiffanygan commented on src/model/User.js
> +    if (this.streakArray[this.streakArray.length - 1] !== date) {
You don't need these lines

2020-11-28 19:00 UTC, tiffanygan approved these changes

2020-11-28 19:01 UTC, merged