Fix getTodayWord bug
awesomememo/frontend-js pull request #29
Opened 2020-12-09 19:59 UTC by ganneo

2020-12-09 20:00 UTC, tiffanygan approved these changes
lgtm

2020-12-10 03:10 UTC, yugan2005 requested changes

2020-12-10 03:10 UTC, yugan2005 commented on src/service/WordService.js
> +      return MEMORIZATION_DATES.includes(daysDone);
`daysDone` only gives the index for getting the current value from `MEMORIZATION_DATES`
You still need check whether the `dayDifference` is equal to that value or not

2020-12-10 03:12 UTC, tiffanygan requested changes

2020-12-10 03:12 UTC, tiffanygan commented on src/service/WordService.js
> +      const daysDone = progresses.filter((progress) => progress.pass === true).length
`progress.pass === true` is the same as `progress.pass`

2020-12-10 18:54 UTC, yugan2005 approved these changes

2020-12-10 19:04 UTC, tiffanygan requested changes

2020-12-10 19:04 UTC, tiffanygan commented on src/service/WordService.js
> +    return todayWordArray.sort(() => Math.random - 0.5);
`Math.random` needs a bracket after it. `Math.random()`

2020-12-10 19:14 UTC, tiffanygan approved these changes

2020-12-10 19:14 UTC, merged